services:
  ricjLoader.css_js_finder:
    class:        plugins\riCjLoader\CssJsFinder
    arguments:    [@kernel]
  ricjLoader.loader_helper:
    class:        plugins\riCjLoader\LoaderHelper
    arguments:    [@settings, @ricjLoader.browser, @ricjLoader.css_js_finder]
    tags:
      - {name: templating.helper, alias: loader}
  ricjLoader.browser:
    class:        plugins\riCjLoader\Browser\Browser
  ricjLoader.css_handler:
    class:        plugins\riCjLoader\Handler\CssHandler
    arguments:    [@templating.helper.router]
    tags:
      - {name: ricjloader.handler, alias: css}
  ricjLoader.js_handler:
    class:        plugins\riCjLoader\Handler\JsHandler
    arguments:    [@templating.helper.router]
    tags:
      - {name: ricjloader.handler, alias: js}
  ricjLoader.minify_filter:
    class:        plugins\riCjLoader\Filter\MinifyFilter
    arguments: [@riCache.Cache,"%web.cache_dir%/ricjloader/", %store.root_dir%, @utility.file]
    tags:
      - {name: ricjloader.filter, alias: minify}